### ISSUE TITLE
Can only add 7 soil sensors on a gateway

### ISSUE THREAD

**Issue by skarsboe** [AdyRock/com.misol#1]
I was unable to add my 8th soil sensor to my gateway even though I was receiving data in the log.
I had a look at the code for onPairListDevices() in \com.misol-master\drivers\soil_moisture\driver.js and found an issue with the for loop.

The for loop   for (var i = 1; i < 8; i++)  needs to be increased to <9  or <=8 in order include the last sensor on the gateway.

I have tested it on my Homey, and I can now add all 8 soil sensors.

```

**Comment by AdyRock** [comment]
Ok, thanks for reporting it and providing detailed information. 
I will fix it as soon as I am back home.
