### ISSUE TITLE
ecowitt wittboy

### ISSUE THREAD

**Issue by Criaga** [AdyRock/com.misol#10]
hello, is it possible to integrate ecowitt wittboy in Homey? Thank you

**Comment by AdyRock** [comment]
I can't be 100% sure as it uses the GW2000 gateway, which I haven't seen before, but it does seem to support the same protocols.
If you already have one then follow the setup guide here https://community.homey.app/t/app-pro-misol-and-ecowitt-release-0-1-29-test-0-1-32/47076

**Comment by tjarb** [comment]
Dear readers,

I'm also interested in the ecowitt wittboy and would like to als for current support in Homey. 

Best regards,

**Comment by AdyRock** [comment]
As far as I know it should work.

**Comment by Alexuskoi** [comment]
Hi the app works fine. But if I want to use the water temperature in a flow, I can't find it anywhere. However, it does state that it is supported. Or am I missing something ? regards alexander

**Comment by AdyRock** [comment]
Have you added the water temperature device to Homey?
![image](https://github.com/AdyRock/com.misol/assets/38184396/b987c8ac-3eae-4d10-9e97-8627d23c5c1c)
Then it should appear in the trigger cards 
![Screenshot_20230722_140015_Homey](https://github.com/AdyRock/com.misol/assets/38184396/230a2c4a-bd3c-493f-b008-556e20bfd6ce)
![Screenshot_20230722_140023_Homey](https://github.com/AdyRock/com.misol/assets/38184396/c723cfba-0d9e-486b-ab3a-8b78730a0f3f)

**Comment by Alexuskoi** [comment]
Ok thank you it works 

greetings Alexander
