### ISSUE TITLE
Ecowitt GW1101 

### ISSUE THREAD

**Issue by Swakra** [AdyRock/com.misol#12]
Hello. Is there any chance to implement Ecowitt GW1101 - Version: GW1100A_V2.2.3 ( https://shop.ecowitt.com/products/gw1101 ) ?

**Comment by AdyRock** [comment]
That should work as it appears to use the same protocol.

**Comment by Swakra** [comment]
Thankyou. I doublechecked and now it works. Sorry
    On Friday, May 19, 2023 at 11:04:05 PM GMT+3, Adrian Rockall ***@***.***> wrote:  
 
 


That should work as it appears to use the same protocol.
