### ISSUE TITLE
Motorized ball valve Misol

### ISSUE THREAD

**Issue by komtiedan** [AdyRock/com.misol#13]
Sorry i am new here, but is it also possible to add the motorized ball valve from Misol?

"Gemotoriseerde klep G3/4 "DN20 (verminderen poort) 2 manier 12VDC CR01, rvs, elektrische klep"

https://nl.aliexpress.com/item/32362191310.html?spm=a2g0o.productlist.main.109.5299d293B4ziYT&algo_pvid=b3991d2d-004b-4cbe-9c81-d8284390ba28&algo_exp_id=b3991d2d-004b-4cbe-9c81-d8284390ba28-54&pdp_npi=3%40dis%21EUR%2124.5%2118.62%21%21%21%21%21%40211be59e16850856835714647d0858%2152376220763%21sea%21NL%21899197693&curPageLogUid=BuuxRBZveFRL
![HTB1IPd1IXXXXXaQXpXXq6xXFXXXL](https://github.com/AdyRock/com.misol/assets/134682971/1918c761-4ce2-46aa-9016-b78246e1d307)

**Comment by AdyRock** [comment]
I don't think so. I can't see any reference to it connecting to the gateways. It looks like it is a product from a different brand that is just being sold by Misol. 
Also the current implementation of the app is for reading only.

**Comment by AdyRock** [comment]
I can't see any reference to it having any communications and the circuit examples shows it being connected to switches. You could ask Misol but I am 90% sure it is not compatible.

**Comment by komtiedan** [comment]
Ok tnx for the update
