### ISSUE TITLE
Add fahrenheit option for flow cards

### ISSUE THREAD

**Issue by joedorman** [AdyRock/com.misol#16]
“Temperature becomes greater than” and “Temperature becomes less than” cards only have Celsius options.

**Comment by AdyRock** [comment]
Normally Athom control the units and frown on dev's changing them.
Is your Homey zone set to location that should have F instead of C?
Do you see F on other cards?
If you answer yes to those two questions then I will contact Athom to see what the issue is.

**Comment by joedorman** [comment]
Good point.

I looked at my other devices with "temperature" and their  "Temperature
becomes greater than" and "Temperature becomes less than" cards are also
incorrect.   Other card tyoes are using the correct units.

**Comment by AdyRock** [comment]
So just to confirm, your zone should be in F and some cards do use that?

**Comment by joedorman** [comment]
That is correct.

**Comment by AdyRock** [comment]
Ok, I will check with Athom to see what should happen.

**Comment by AdyRock** [comment]
Could you let me know what device it is and which capability?

**Comment by joedorman** [comment]
ECOWITT WN31 - Wireless Multi-Channel Thermometer and Hygrometer Sensor,
Indoor and Outdoor Temperature & Humidity Gauge with LCD Display, Remote
App Monitoring, Dip Switches to Switch ℃/℉

**Comment by joedorman** [comment]
10.1.0-rc.4 has fixed this issue.  Thanks for your help bringing this to Homey's attention
