### ISSUE TITLE
froggit support

### ISSUE THREAD

**Issue by Raycokes2000** [AdyRock/com.misol#17]
Hello Adrian,

Hope your are doing fine over there.

I was wandering cause I found out that the weahter station i have from froggit, the ws3000 SE, looks a lot like Misol.
Are you aware and is it possible to add? and how.

Regards Raymond

**Comment by AdyRock** [comment]
If it has settings like these 
![Screenshot_20231108_211829_WS View.jpg](https://github.com/AdyRock/com.misol/assets/38184396/a1683c13-ce2a-4bca-923c-46bc056ec78c)

Then it should work.

**Comment by Raycokes2000** [comment]
hmm okay, i think so, that from the webpage right, the GW can already be updated, at least mine could to 2.2.8.
or is this the ws tool app?

**Comment by AdyRock** [comment]
The picture is from the ws app, but if you can see it from a Web page then I guess it should still work.

**Comment by AdyRock** [comment]
Afraid I can't help with the section not opening, but if it supports the feature that's were it will need setting up.

**Comment by Raycokes2000** [comment]
ok thanks anyway, going to contact to manufacturer

**Comment by Raycokes2000** [comment]
yes, that page is available now. but cant set it op for homey to see new devices aka the gateway.

**Comment by AdyRock** [comment]
In what way can't you set it up?

**Comment by Raycokes2000** [comment]
with misol app the gatway is not found, what do i need to set in gateway before it gets found

**Comment by AdyRock** [comment]
Basically everything in the picture above except the IP address of your Homey.

**Comment by Raycokes2000** [comment]
yes got it. thanks Adrian! keep up the good work!
I had the GW addres in there instead of homey duhhuh ;-)
