### ISSUE TITLE
Problem "dd is not defined"

### ISSUE THREAD

**Issue by TuxTiger** [AdyRock/com.misol#18]
Strange error, can't say when this has occured.

![Screenshot_20231216_142411_Homey](https://github.com/AdyRock/com.misol/assets/4631482/577d301b-a4cc-4fc7-b396-b92654db6a8b)
![Screenshot_20231216_142139_Homey](https://github.com/AdyRock/com.misol/assets/4631482/e45040c1-56c6-46d5-a290-3f92c935dc2a)

**Comment by AdyRock** [comment]
I have published a new test version in the Athom store.

**Comment by TuxTiger** [comment]
All is good again sir, thank you very much for your rapid response!
