### ISSUE TITLE
Whislist "The temperature is lower or higher than"

### ISSUE THREAD

**Issue by marcodeklijn** [AdyRock/com.misol#20]
i would like to use the option "The temperature is lower or higher than" instead of temperature is changed.
The flow i want to make is like. When time=6.00 and temperature sensor x is lower than xx celsius than...

**Comment by AdyRock** [comment]
You can do this using the logic card to check the global token.
<img width="308" alt="image" src="https://github.com/AdyRock/com.misol/assets/38184396/abd33015-94e3-43ef-bbc0-d64c9cc0d24d">
