### ISSUE TITLE
Problem to connect to Gateway after upgrade firmware

### ISSUE THREAD

**Issue by MatsGrano** [AdyRock/com.misol#21]
Hi

I can't connect to the Gateway after I have upgrade my Gateway to version V.2.3.1

**Comment by AdyRock** [comment]
Have you checked to make sure the Gateway settings for the custom weather services haven't been reset?

**Comment by MatsGrano** [comment]
When I try to add new device it can't find the Gateway :(

**Comment by AdyRock** [comment]
The app requires the gateway to push data to it. If nothing has been pushed then the app won't find any devices. 

Did you check the custom weather service section if the gateway to make sure it is still pointing to your Homey?

**Comment by MatsGrano** [comment]
I don't know what was wrong but it start to work :) Thanks for the reply :)
