### ISSUE TITLE
Connecting gateway

### ISSUE THREAD

**Issue by Jockamin** [AdyRock/com.misol#22]
Can someone explain for me, step by step, how I connect the Ecowitt gateway to Homey Pro  

I have written this in WS View and in the app: 

![IMG_1242](https://github.com/AdyRock/com.misol/assets/162914127/37c378e4-9c88-460b-9055-6bc9023b2a0c)
![IMG_1241](https://github.com/AdyRock/com.misol/assets/162914127/ede0c706-bc0a-4fc9-ba1f-941982b1a700)

Thank you from a newbie 🙏

**Comment by AdyRock** [comment]
The settings to put in that page are in three readme https://github.com/AdyRock/com.misol

**Comment by Jockamin** [comment]
Thank you! 🙏
