### ISSUE TITLE
Soil moisture flow

### ISSUE THREAD

**Issue by Jockamin** [AdyRock/com.misol#23]
I have this flow in Homey. 
I want Homey to shut off the water valve if the soil moisture IS greater than 19 %. But it doesn’t happen. 

I’m wondering if it has something to do with the meaning “becomes greater” in stead of “is greater”. 
The moisture doesn’t become greater than 19% during the time frame (it could already be 27%) but I still don’t want any more water. 

Can I do anything or should their be a new possibility in the flow to make this happen? 
![IMG_1359](https://github.com/AdyRock/com.misol/assets/162914127/abbcc148-060d-4953-b9d2-c46efda64edf)

**Comment by AdyRock** [comment]
There isn't a card for is greater than as there is no way to know when that would trigger. In theory it would trigger constantly when the value is greater than the setting, but that would overwhelm Homey. 
What you need is to find a way to trigger a Flow and then check if the value is greater than x, but make sure the trigger doesn't happen to often else Homey will disable the Flow.
