### ISSUE TITLE
Gateway should be device class "sensor", not "other"

### ISSUE THREAD

**Issue by mech78** [AdyRock/com.misol#24]
The Homey mobile app recently supported climate readings and averages of temperature and humidity being shown in the devices section close to activity, energy and lights, etc.

I can successfully include the weather station and some temperature & humidity sensors. But not the gateway itself despite it has it's own internal sensors. I assume that is because the gateway is reporting class "other" instead of "sensor". 
Not sure if changing that would have side effects, but I guess that's why it is not selectable as climate device and cannot expose "measure_temperature" and "measure_humidity" readings.

**Comment by mech78** [comment]
It's an Ecowitt "GW1100A_V2.3.1"

**Comment by mech78** [comment]
BTW: I asked Athom support if they could change that climate feature to use "duck typing" and just look at the device properties like "measure_temperature" and "measure_humidity" instead of just using the device class. I do have trouble with other devices that have configurable device classes. E.g. some power sockets do have temperature sensors or even buttons, but actually the device class is intended e.g. for saying e.g. a light or TV is plugged or controls blinds. If you do that it won't consider it as a sensor, tough, meaning all those fancy mixed class devices are either climate sensor or not. - As I don't know if for the gateway is any forseeable side effect of not having it a sensor I think it could be still fine to change it.

**Comment by AdyRock** [comment]
I have changed it in the new test version.

**Comment by mech78** [comment]
Thanks, tried it. Works fine.
