### ISSUE TITLE
Trouble getting data to Homey pro 2023 (wired to router) using Misol an Ecowitt App

### ISSUE THREAD

**Issue by hanshoevenaars** [AdyRock/com.misol#25]
Since I use Homey Pro 2023 I have a problem to get data from my weather station. It all worked fine with Homey early 2019.
In the Ecowitt app on my phone all data is there. On my Homey Pro 2023 temperature sensors are ok but wind and solar and rain do not work.

Any help is welcome.

**Comment by hanshoevenaars** [comment]
![Screenshot_20240404_103841_Homey](https://github.com/AdyRock/com.misol/assets/38373963/805b4e4c-2e78-4fd2-8f11-f8b7a4c5315b)

**Comment by AdyRock** [comment]
Strange as all the information arrives in one packet. 
Could you send the Detected log from the app settings page.

**Comment by hanshoevenaars** [comment]
unfortunately that doesn't work either. 
![Screenshot_20240404_160914_Homey](https://github.com/AdyRock/com.misol/assets/38373963/dd21cffc-83d8-4148-bc94-0c63ea19332f)
![Screenshot_20240404_161057_Homey](https://github.com/AdyRock/com.misol/assets/38373963/e1863980-3a92-4c48-8d25-50a26e119a6f)
![Screenshot_20240404_161104_Homey](https://github.com/AdyRock/com.misol/assets/38373963/93c8c1f3-c68e-4599-80f9-8121c430a890)
![Screenshot_20240404_161113_Homey](https://github.com/AdyRock/com.misol/assets/38373963/b164599d-5e45-4fa0-ae9d-c0a3bd79c36d)
![Screenshot_20240404_161126_Homey](https://github.com/AdyRock/com.misol/assets/38373963/0b8dbe2d-3f6e-486c-8ab6-2a13dea31684)

**Comment by hanshoevenaars** [comment]
I hope I don't have to download the app again. Then I have to reset all flows (43)

**Comment by hanshoevenaars** [comment]
Thanks for the quick response

**Comment by hanshoevenaars** [comment]
I use the Homey Pro Ethernet Adapter. Maybe this is a problem?

**Comment by AdyRock** [comment]
It looks possibly like a DNS issue as the IP address shown is just a loop back. 
Can you send a picture of the weather settings on the gateway and make sure that's using a fixed IP address for Homey instead of a URL.

**Comment by hanshoevenaars** [comment]
I have put a backup from my old Homey 2019 to my new Homey Pro 2023. The setting in the app was the IP of my old Homey. So i got rid of the app and reinstalled it. Now using the ip of the Homey Pro. It is working now. Many thanks
