### ISSUE TITLE
Add indoor temperature and humidity sensor

### ISSUE THREAD

**Issue by Stolt64** [AdyRock/com.misol#26]
I have a HP2551 Whether station and I have just started the Misol & Ecowitt app. Everything works just fine. When I added the temperature and humidity sensor I just got the outdoor reading from the wheather tools (Channel 0). When I search for more nothing happens. How can I add my Indoor sensor? I can see the readings in the diagnostics but not in your Homey app.
 "tempinf": "73.4",
 "humidityin": "28",

![Diag](https://github.com/AdyRock/com.misol/assets/95311174/03e8689b-aad8-47dc-9e81-34cd0f45f4ca)

**Comment by AdyRock** [comment]
I think they are in the Gateway device.

**Comment by Stolt64** [comment]
Ok, found it thanks 😃
