### ISSUE TITLE
gateway in Homey app

### ISSUE THREAD

**Issue by tomja1956** [AdyRock/com.misol#27]
Which frequency is most suitable for the Ecowitt gateway GW 2100? 433 or 868 MHz?

**Comment by AdyRock** [comment]
Whatever is legal in your country 😁
They all work equally well.

**Comment by tomja1956** [comment]
Hi again
Is a sensor connected to the gateway GW 2100 required for Homey to detect
the gateway/sensor?


sön 28 apr. 2024 kl. 10:37 skrev Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
Sorry, not sure what you mean?

**Comment by tomja1956** [comment]
I currently only have a gateway GW1100, without any sensors, connected to
the network in the Ecowitt app. However, the Homey app "Misol snd Ecowitt"
does not find the gateway GW1100.


tors 2 maj 2024 kl. 07:52 skrev Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
Have you configured the gateway to publish data to Homey?

**Comment by tomja1956** [comment]
The "Weather Observations Website" page was not filled out correctly. Now
everything works. Thank you very much for quick replies :)



tors 2 maj 2024 kl. 08:48 skrev Adrian Rockall ***@***.***>:
