### ISSUE TITLE
GW2000 with WH51 not connecting to Homey app

### ISSUE THREAD

**Issue by PeterMassar** [AdyRock/com.misol#28]
GW2000 is wired connected to my router. The wh51 is connected to the GW2000. GW2000 has a static IP adres. In the ws view app i can see all the data from the WH1 and the GW2000 however the homey app can't reach hte gw2000 or wh551 sensors. It says permission denied? In the homey app i put in the static IP adres and also tried the static ip adres with the portnuer. But still no devices are found in the app? Is there more information? In the GW2000 dashboard i enabled the customization and also entered there the port number and static IP adres. But still no luck? Thanks in advance, Peter

**Comment by AdyRock** [comment]
I'm confused where you see the permission denied error?
The Homey app doesn't take an IP address, just a port number to create a listener on.
In the GW2000 are you entering Homey's IP address, as the GW posts messages to Homey?

**Comment by PeterMassar** [comment]
Hi AdyRock, problem solved! i put the IP adres of homey in and port 7777 i also set the ecowit weather station to 1? Then i saw finally the gateway and the 7 soil sensors. Thanks for the good work! Peter

**Comment by bertus56** [comment]
Hi peter where do you put the IP adres of homey

**Comment by AdyRock** [comment]
The Homey IP address is entered into the gateway settings.
