### ISSUE TITLE
WS90 - Access Indoor Sensors 

### ISSUE THREAD

**Issue by ypstullibus** [AdyRock/com.misol#29]
I was able to connect my new WS90 via GW2000 to HomeyPro and create a weather station device - GREAT JOB - Thx for your APP.

Now I try to connect to the indoor sensors connected to WS90 (indoor temperature, Indoor humidity) - but I don't know how to get this additional data. Any help on that ?

Thx a lot

MR

**Comment by AdyRock** [comment]
They should be added with the Temperature & Humidity device. 
If that is not working, could you open the app settings page, select the Detected tab and then tap on Send Log.

**Comment by ypstullibus** [comment]
It failed to send, here is some output within the log. I also sent a diagnose file (key: 588c4d41-ea2d-4bbe-ae7c-864759efdf2a)

 

Here ist he picture from the devce I added (no indoor values):

 



 

* 5:26:54.742: 

Send log error: Error: connect ECONNREFUSED 127.0.0.1:465

    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)

 

* 5:27:2.995: 

{

  "PASSKEY": "XXX",

  "stationtype": "GW2000A_V3.0.8",

  "runtime": "54506",

  "dateutc": "2024-05-08+05:27:02",

  "tempinf": "77.18",

  "humidityin": "40",

  "baromrelin": "28.933",

  "baromabsin": "28.933",

  "tempf": "52.52",

  "humidity": "83",

  "winddir": "66",

  "windspeedmph": "0.00",

  "windgustmph": "2.24",

  "maxdailygust": "2.91",

  "solarradiation": "8.68",

  "uv": "0",

  "rrain_piezo": "0.000",

  "erain_piezo": "0.000",

  "hrain_piezo": "0.000",

  "drain_piezo": "0.000",

  "wrain_piezo": "0.000",

  "mrain_piezo": "0.000",

  "yrain_piezo": "0.000",

  "ws90cap_volt": "0.5",

  "ws90_ver": "138",

  "wh90batt": "3.00",

  "freq": "868M",

  "model": "GW2000A",

  "interval": "15"

}

 

Von: Adrian Rockall ***@***.***> 
Gesendet: Dienstag, 7. Mai 2024 20:07
An: AdyRock/com.misol ***@***.***>
Cc: ypstullibus ***@***.***>; Author ***@***.***>
Betreff: Re: [AdyRock/com.misol] WS90 - Access Indoor Sensors (Issue #29)

 

They should be added with the Temperature & Humidity device.
If that is not working, could you open the app settings page, select the Detected tab and then tap on Send Log.

**Comment by AdyRock** [comment]
Have you tried to add the Temperature & Humidity device?
It shows as a separate device in Homey.
