### ISSUE TITLE
WS90 stops delivering data to homey

### ISSUE THREAD

**Issue by Ruediger-P** [AdyRock/com.misol#30]
Hi Adrian,

I have a WS90 outside and a 6250 inside. Since yesterday WS90 stopped delivering data to my homey pro 23 (not to the 6250!). I installed the experimental app, no change. I deleted the WS90 and I can’t connect it anymore. I changed to the official app, nothing works…
Do you have any suggestions?

Mit nettem Gruss 
Rüdiger Prenzel

**Comment by AdyRock** [comment]
Has the IP address of Homey changed?

**Comment by Ruediger-P** [comment]
No. It is fixed.

**Comment by AdyRock** [comment]
The app detects the hub from messages posted to it. So the problem is either caused by the hub not sending messages or Homey not receiving them.
Have you tried rebooting them?

**Comment by Ruediger-P** [comment]
I pulled the plug. Nothing changed…

**Comment by AdyRock** [comment]
I honestly don't know as I haven't seen that happen before. 
All I can suggest is check all the settings in the gateway to make sure it hasn't lost anything. Also make sure you use Homey's IP address and not the URL just in case that is not resolving correctly.

**Comment by Ruediger-P** [comment]
Which settings should I check? And where should I use Homeys IP address?

**Comment by AdyRock** [comment]
The weather station settings in the gateway.

**Comment by Ruediger-P** [comment]
I installed everything from scratch after resetting and it’s working fine again 😀
I don’t know why this happened but…
Thanks for your support
