### ISSUE TITLE
Solar radiation from Wittboy does not upgrade in Homey

### ISSUE THREAD

**Issue by Wvanoors** [AdyRock/com.misol#31]
Hi Adrian. Thanks for your app. I am trying to let my windscreens down, when solar radiation risie above certain values, depending on the soalr hight. But the Solar radiation in my Homey does not change. The value always is 35.1 (when making a notification of it in the Homey time-line). But values are over 700 W/m2 when I read them in the Ecowitt app. Any idea what I do wrong? Or should I issue the question in Homey Community Forum, maybe? Thanks, Regards, Willem

**Comment by AdyRock** [comment]
Can you send the log from the app settings screen so I can see what is being reported.

**Comment by Wvanoors** [comment]
K Adrian, here is the code: a6523772-bf68-4303-8842-ed3075d6f206

**Comment by Wvanoors** [comment]
By the way: Ecowitt made a new API. The devices asked for upgrade, but i did not run them. Are you aware of that? And can I do that without problems?

**Comment by AdyRock** [comment]
I'm not aware of a new one so I can't comment but I will investigate.

**Comment by Wvanoors** [comment]
> K Adrian, here is the code: a6523772-bf68-4303-8842-ed3075d6f206

I tried another diagnostisch report: made it in my Homey, from the Misol and ~Ecowitt app.
Code: 3ef31e52-47f5-4b4a-99b4-c5485089e840

Tried to send you the log also, but it gave an errormessage. Stil, the logfile now vanished, so I hope you got it now.

**Comment by AdyRock** [comment]
What error do you get?

**Comment by Wvanoors** [comment]
It was very short. Did not copy it and cant replicate it. There was no logfile anymore. Error was something like; couldn't send or something...

Op 12 mei 2024 14:15, om 14:15, Adrian Rockall ***@***.***> schreef:

**Comment by Wvanoors** [comment]
Not at home now. Ill try again soon. Again: Thanks for helping! Kind regards Willem 

Op 12 mei 2024 14:15, om 14:15, Adrian Rockall ***@***.***> schreef:
