### ISSUE TITLE
Feature request: Lightning distance in the flow notification message

### ISSUE THREAD

**Issue by eddiegonzales** [AdyRock/com.misol#37]
Hi,

It would be nice if its possible to have the Homey Pro sending the latest distance of a lightning detected. Right now you can only setup a trigger saying if the lightning get under or over a certain distance. And then you have to look up the distance the lightning has to your position. Thanks

**Comment by AdyRock** [comment]
The distance should be available in a global tag that you can use in Flows.

**Comment by eddiegonzales** [comment]
Thank you very much. Found it!
