### ISSUE TITLE
Request support HP2564 Display for data collection

### ISSUE THREAD

**Issue by BeArt60** [AdyRock/com.misol#38]
As the new HP2564 display of Ecowitt can act as a gateway, it should in my opinion be possible to get the data from this unit. Now only the Gateway is supported, and I don't want an extra device to do so.
With regards, BartM

**Comment by Stable-Adrian** [comment]
If the HP2564 can act as a gateway then it should be supported by the already. Have you configured the settings in HP2564 to post messages to Homey as shown in the instructions on the forum?

**Comment by AdyRock** [comment]
I have searched for the manual but all I can find is the HP2560, so not sure how it compares:
chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://osswww.ecowitt.net/uploads/20230221/HP2560_C%20Manual.pdf.pdf
Look on page 50 and set the IP address to your Homey IP, the port to 777 and the Interval to the lowest value. The one field that is missing is the Path, so I'm not sure if that will default to the correct value, but if you do have that then set it to /data/report.

**Comment by BeArt60** [comment]
Sorry for giving no response.
But found a workaround by uploading the data to Wunderground, which can be configured on the Ecowitt display HP2560. Using the Wunderground app on the Homey Pro I was able to retrieve the data from the Ecowitt weather station.
