### ISSUE TITLE
No wind speed values since update

### ISSUE THREAD

**Issue by RensBree** [AdyRock/com.misol#43]
Hi
I have no wind speed values from my DNT weather station since last update.
The same with the Wunderground app (you are also the  maker of that app?)
Like the misol app very much.

**Comment by AdyRock** [comment]
Has the item vanished or is it just not being updated?

**Comment by RensBree** [comment]
Values are updated 4 days ago.
![Screenshot_20240823-135500](https://github.com/user-attachments/assets/27173e01-51ce-4a4a-a36c-2a6d330edcae)

**Comment by AdyRock** [comment]
Have other parameters updated?
Has the IP address of Homey changed and the station is still posting to the old IP?

**Comment by RensBree** [comment]
All other parameter are updated. IP did not changed.
I deleted the weather station from my hardware in Homey en connected it again, with the same results.
In the case of WU I deleted the weather station and also the app. Started allover again with a new api- key. On the internet is the wind speed updated. Not in the Homey app.

**Comment by AdyRock** [comment]
Could you open the app settings page and select the Detected tab and if there is data in the lower panel, tap on Send Log.

**Comment by AdyRock** [comment]
It would also be worth checking the Wind Speed units have something set and maybe change it to something else and put it back again.

**Comment by RensBree** [comment]
I found the detected tab, there are normal values.
I changed  in the app settings the metric values to UK.
Then there was data. Changed it back to metric and voila, I got data and it was updated continu.
Solved?

**Comment by AdyRock** [comment]
I'm guessing there's an issue with the app with setting the default unit, so I will investigate.
Hopefully yours will continue to work now. Thanks for reporting it.

**Comment by AdyRock** [comment]
I have found the issue. The app is initialising the units type to 0 instead of '0'.
