### ISSUE TITLE
Rain monthly fallen tag

### ISSUE THREAD

**Issue by Raycokes2000** [AdyRock/com.misol#49]
Hi there,

I am missing tags for the weather station eg monthly rain fallen, per season, year etc to use for sending values, or maybe a short monthly report.

Is that something that can be done?
Regards Raymond

**Comment by AdyRock** [comment]
They should be there:
![image](https://github.com/user-attachments/assets/d3f5ed7b-4053-431b-8180-a041e1c5c9d6)

**Comment by Raycokes2000** [comment]
Hmm okay, it's for sending these values in say a push message or Time-line.
Then nothing is showing up

**Comment by AdyRock** [comment]
![image](https://github.com/user-attachments/assets/f1af0c2f-7051-4d4d-8c7c-73d8622b0d03)

Seems to be OK for me

**Comment by Raycokes2000** [comment]
Hmm strange, think this a homey app bug here... Strange

https://github.com/user-attachments/assets/33c8ee0a-4041-4a42-b811-3d905c23e9d1

**Comment by AdyRock** [comment]
Is your weather station called misol?
I only type that because I have a few and I call them by the brand.

**Comment by Raycokes2000** [comment]
I mixed up. The gateway and sensors are connected with misol app. The weather's station is through the weather underground I just see. Sorry

**Comment by Raycokes2000** [comment]
My mistake, a mixed up the used app 🤔😉🤣
