### ISSUE TITLE
Ecowitt Moisture measurement in a flow

### ISSUE THREAD

**Issue by greenwell72** [AdyRock/com.misol#6]
Hi Adrian,

Currently I have gardena moisture sensors but they don't allow me to what I think is logical. Before changing to Ecowitt I wanted to check with you if they do.

Basically I want a flow to trigger ever day at 20:00 which checks the moisture content is below a certain % and if it is, start watering. With Gardena the option for time is x and moisture is below y isn't possible as gardena sensor isn't available when I choose AND in the flow. I can do it the other way around (moisture is below x and time is y, but never triggers as the sensor only updates its value every few hours and it never triggers at the exact right time. Would the Ecowitt soil sensor and your app let me do what I am trying to do?

**Comment by AdyRock** [comment]
The moisture sensor does have the required AND card.
But before you jump ship, have you looked to see if the Gardena has a tag that could be used with the logic card?

**Comment by greenwell72** [comment]
Thank you Adrian. I don't know how to look for use tags if I am honest.

**Comment by greenwell72** [comment]
Is it using the Logic function in the AND section of a flow?

**Comment by AdyRock** [comment]
Yes, select this card:
![Screenshot_20220522-151051_Homey](https://user-images.githubusercontent.com/38184396/169699389-4a2f25dc-f548-430a-bb88-6a26f02ef03b.jpg)
Then tap on the tag image:
![Screenshot_20220522-151124_Homey](https://user-images.githubusercontent.com/38184396/169699398-7e68cdb2-8ab3-4222-bfa1-55ceddb9f32f.jpg)
Then search for moisture, or whatever it is called in the Gardena device;
![Screenshot_20220522-151115_Homey](https://user-images.githubusercontent.com/38184396/169699404-51f8a6b3-59c6-49e8-9873-0d31da419dfa.jpg)

**Comment by greenwell72** [comment]
Thank you so much Adrian. Have created new flows now. Fingers crossed.

**Comment by AdyRock** [comment]
Hopefully this is working OK for you so I will close the issue, but please let me know if there is anything else.
