### ISSUE TITLE
PM10 and CO2.5 can't be added

### ISSUE THREAD

**Issue by wieling** [AdyRock/com.misol#7]
Hi Adrian,

I'm using the newest version of your app and I noticed that my PM10+CO2 was not connected. I therefore removed it, but when adding a new device, I can't add it (there's a red triangle with an exclamation mark shown). Any idea what the problem could be? The device is visible in the WS View app. All my other devices are also visible in Homey.

With kind regards,
Martijn

**Comment by AdyRock** [comment]
Hmm, I can replicate that so will get it fixed ASAP.

**Comment by AdyRock** [comment]
I have published a new test version https://homey.app/a/com.misol/test/

**Comment by wieling** [comment]
Thanks, it works again!
