### ISSUE TITLE
New device request, Ecowitt WS80

### ISSUE THREAD

**Issue by TuxTiger** [AdyRock/com.misol#8]
https://www.ecowitt.com/shop/goodsDetail/46

I will send the log from my app!

Thanks,
TUx

**Comment by AdyRock** [comment]
It looks like I can add that with the current weather station option. I'm not sure where the rain data is coming from though, do you have a separate device for that?

I think the battery information is reporting as "wh80batt", so I can use that as a filter if needed.

**Comment by TuxTiger** [comment]
Yes, it's coming from a separate rain sensor you added a couple of weeks ago at my request,,,for which I thank you!

**Comment by AdyRock** [comment]
Ah, OK.
So for now you could add the pair as a weather station and just the battery information will be missing. 
I will add the WS80 as a separate device using the  WH80battery entry as a filter which should be ready in a couple of days.

**Comment by AdyRock** [comment]
I found some time today, so there is a new test version in the store.

**Comment by TuxTiger** [comment]
Great! Do I understand you corrrectly that I have to delete the Rain meter in my Homey, and add the Weather Station to get the rain meter data back again with the wind data of the WS80?

**Comment by AdyRock** [comment]
No, the two devices are added separately. So keep the rain meter and add the WS80

**Comment by TuxTiger** [comment]
Great! It worked like a charm!

I send you the link of how the unit looks like I think?  The WX80 looks very different ;)

![Screenshot_20220730-190036_Chrome](https://user-images.githubusercontent.com/4631482/181934003-4dee3586-90f8-4c58-87de-949e68bbbdd1.jpg)

**Comment by TuxTiger** [comment]
Thanks again for the great service and SPEED :)

**Comment by AdyRock** [comment]
Ah, yes I grabbed the new image but forgot to change the path to it when I copied the weather station as a starting point. 
Thanks for the heads up.
