### ISSUE TITLE
Barometric pressure

### ISSUE THREAD

**Issue by basvdploeg** [AdyRock/com.misol#9]
Hi! I noticed that the barometric pressure of my Weather Station shown in the Homey app doesn't match the pressure that is shown on the Weather Station itself (and Weather Underground).

After a quick look I found that the app is using the `baromabsin` (absolute) data, instead of `baromrelin`, which is the corrected, relative data.

Is there a chance that you can change those, or - if possible - show both datapoints (relative and absolute) in the Homey app?

**Comment by AdyRock** [comment]
I will have a look.

**Comment by AdyRock** [comment]
I have published a new test version with all instances now using baromrelin.

**Comment by AdyRock** [comment]
It is now live, obviously the changes were small enough for it to skip manual verification.

**Comment by basvdploeg** [comment]
Thank you! Works great! 👍
